update read version in git action

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -3,7 +3,7 @@ name: Go CI/CD Pipeline
 on:
   push:
     branches: [main, develop]
-    tags: ['v*.*.*']  # match any version like v1.0.0, v1.2.3
+    # tags: ['v*.*.*']  # match any version like v1.0.0, v1.2.3
 
 env:
   APP_NAME: go-fiber
@@ -27,10 +27,20 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
+      - name: Read version from file
+        id: read_version
+        run: |
+          if [ ! -f version ]; then
+            echo "❌ version file not found!"
+            exit 1
+          fi
+          VERSION=$(cat version)
+          echo "version=${VERSION}" >> $GITHUB_OUTPUT
+
       - name: Set Docker Tags
         id: vars
         run: |
-          VERSION=latest
+          VERSION=${{ steps.read_version.outputs.version }}
           if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
             VERSION=${GITHUB_REF#refs/tags/}
           elif [[ "${GITHUB_REF}" == refs/heads/develop ]]; then
@@ -47,7 +57,6 @@ jobs:
           tags: |
             ${{ env.DOCKER_IMAGE }}:${{ steps.vars.outputs.version }}
             ${{ env.DOCKER_IMAGE }}:latest
-          
   deploy:
     name: 🚀 Deploy (Optional)
     runs-on: ubuntu-latest
